#server:
#  port: 8110  #服务端口
#  tomcat:
#    max-threads: 10 #tomcat的最大并发值修改为10，默认是200
#
#spring:
#  application:
#    name: service-edu  #服务名
#  profiles:
#    active: dev  #开发环境
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
#    username: root
#    password: '000000' #注意密码开头为0开头的会被解析为8进制，要么就是使用引号或者修改密码
#  jackson:  #返回json的全局时间格式
#    time-zone: UTC
#    date-format: yyyy-MM-dd HH:mm:ss
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
#        dashboard: localhost:8080 #指定控制台服务的地址
#  redis:
#    cluster:
#      nodes:
#        - 192.168.199.143:7000
#        - 192.168.199.143:7001
#        - 192.168.199.143:7002
#        - 192.168.199.143:7003
#        - 192.168.199.143:7004
#        - 192.168.199.143:7005
#    lettuce:
#      pool:
#        max-active: 20 # 最大连接数，负值表示没有限制,默认8
#        max-wait: -1 #最大阻塞等待时间，负值表示没限制,默认-1
#        max-idle: 8 # 最大空闲连接,默认8
#        min-idle: 0 # 最小空闲连接,默认0
#
## mybatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml
#
##    设置日志级别 info debug warn error fatal 默认日志级别就是info
##logging:
##  level:
##    root: debug
#
##service-product: #调用的提供者的名称
##  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
#ribbon:
#  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
#  MaxAutoRetriesNextServer: 1 #重试其他实例的最大重试次数，不包括首选所选的server，默认1
#  ConnectTimeout: 5000 #连接建立的超时时长，默认1秒
#  ReadTimeout: 5000 #处理请求的超时时间，默认为1秒
#
#feign:
#  sentinel:
#    enabled: true
