#server:
#  port: 8160 #服务端口
#
#spring:
#  profiles:
#    active: dev # 环境配置
#  application:
#    name: service-ucenter #服务名
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 8081
#        dashboard: localhost:8080
#  datasource:
#    url: jdbc:mysql://localhost:3306/guli_ucenter?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
#    username: root
#    password: '000000'
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson: #返回json的全局时间格式
#    time-zone: UTC
#    date-format: yyyy-MM-dd HH:mm:ss
#  redis:
#    cluster:
#      nodes:
#        - 192.168.199.143:7000
#        - 192.168.199.143:7001
#        - 192.168.199.143:7002
#        - 192.168.199.143:7003
#        - 192.168.199.143:7004
#        - 192.168.199.143:7005
#    lettuce:
#      pool:
#        max-active: 20 # 最大连接数，负值表示没有限制,默认8
#        max-wait: -1 #最大阻塞等待时间，负值表示没限制,默认-1
#        max-idle: 8 # 最大空闲连接,默认8
#        min-idle: 0 # 最小空闲连接,默认0
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/atguigu/guli/service/ucenter/mapper/xml/*.xml
#
#wx:
#  open:
##    微信开放平台 appid
#    appId: wxed9954c01bb89b47
##    微信开放平台 appsecret
#    appSecret: a7482517235173ddb4083788de60b90e
##    微信开放平台 重定向url （guli.shop需要在微信开放平台配置）
##    如果是本地调试就可以将guli.shop替换成本机地址即可
#    redirectUri: http://localhost:8160/api/ucenter/wx/callback