#server:
#  port: 8170 # 服务端口
#
#spring:
#  profiles:
#    active: dev # 环境设置
#  application:
#    name: service-trade # 服务名
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # nacos服务地址
#    sentinel:
#      transport:
#        port: 8081
#        dashboard: localhost:8080
#
#  #spring:
#  redis:
#    cluster:
#      nodes:
#        - 192.168.199.143:7000
#        - 192.168.199.143:7001
#        - 192.168.199.143:7002
#        - 192.168.199.143:7003
#        - 192.168.199.143:7004
#        - 192.168.199.143:7005
#  datasource: # mysql数据库连接
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_trade?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
#    username: root
#    password: "000000"
#  #spring:
#  jackson: #返回json的全局时间格式
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
#  mapper-locations: classpath:com/atguigu/guli/service/trade/mapper/xml/*.xml
#
#ribbon:
#  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
#  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒
#
#feign:
#  sentinel:
#    enabled: true
#
#weixin:
#  pay:
#    #关联的公众号appid
#    appId: wx74862e0dfcf69954
#    #商户号
#    partner: 1558950191
#    #商户key
#    partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
#    #回调地址  gulischool.frp.tryzth.com为内网穿透  => localhost:8170
#    notifyUrl: http://gulischool.frp.tryzth.com/api/trade/weixin-pay/callback/notify